"use client";
import React from "react";
import { motion } from "framer-motion";
import { useInView } from "react-intersection-observer";

export const Thumbnails = () => {
  const { ref, inView } = useInView({
    triggerOnce: true, // Ensures it animates only once when in view
    threshold: 0.2, // 20% of the element must be visible before triggering
  });
  return (
    <div ref={ref} className="max-w-screen-xl mx-auto p-4">
      <div className=" text-center pt-12 pb-4">
        <motion.p
          initial={{ opacity: 0, scale: 0.8 }} // Start small and transparent
          animate={inView ? { opacity: 1, scale: 1 } : {}} // Scale up when in view
          transition={{ duration: 0.6, ease: "easeOut" }} // Smooth transition
          className="font-openSans text-3xl sm:text-4xl md:text-[66px] font-bold text-[#333333]"
        >
          Generated by AI Image Creator
        </motion.p>
      </div>

      <motion.p
        initial={{ opacity: 0, opacity: 1 }} // Start small and transparent
        animate={inView ? { opacity: 1, scale: 1 } : {}} // Scale up when in view
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="font-openSans text-sm text-center text-gray-500 mb-6"
      >
        Explore AI-generated images for inspiration. Click to view and use the
        prompts for your own creations.
      </motion.p>

      <motion.div
        initial={{ opacity: 0, scale: 0.28 }} // Start small and transparent
        animate={inView ? { opacity: 1, scale: 1 } : {}} // Scale up when in view
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="grid grid-cols-4 gap-4 auto-rows-[200px]"
      >
        {/* First Row */}
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image1.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image 695.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image 694.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>

        {/* Second Row */}
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image 693.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image (1).png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image 699.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>

        {/* Third Row */}
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image (2).png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image 698.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/22.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image1.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image1.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
      </motion.div>
    </div>
  );
};
