import React from "react";

export const Thumbnails = () => {
  return (
    <div className="max-w-screen-xl mx-auto p-4">
      <div className=" text-center pt-12 pb-4">
        <p className="font-openSans text-3xl sm:text-4xl md:text-[66px] font-bold text-[#333333]">
          Generated by AI Image Creator
        </p>
      </div>

      <p className="font-openSans text-sm text-center text-gray-500 mb-6">
        Explore AI-generated images for inspiration. Click to view and use the
        prompts for your own creations.
      </p>

      <div className="grid grid-cols-4 gap-4 auto-rows-[200px]">
        {/* First Row */}
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image1.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image 695.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image 694.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>

        {/* Second Row */}
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image 693.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image (1).png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image 699.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>

        {/* Third Row */}
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image (2).png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-2">
          <img
            src={"/assets/examples/image 698.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/22.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image1.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
        <div className="col-span-1 row-span-1">
          <img
            src={"/assets/examples/image1.png"}
            className="w-full h-full object-cover rounded-lg"
          />
        </div>
      </div>
    </div>
  );
};
